In [2]:
import pandas as pd

beneficiary_2008 = pd.read_csv('../data/raw/Beneficiary_2008.csv')
beneficiary_2009 = pd.read_csv('../data/raw/Beneficiary_2009.csv')
beneficiary_2010 = pd.read_csv('../data/raw/Beneficiary_2010.csv')

inpatient = pd.read_csv('../data/raw/Inpatient_2008_to_2010.csv')
outpatient = pd.read_csv(
    "../data/raw/Outpatient_2008_to_2010.csv",
    dtype="string",
    low_memory=False
)

In [3]:
beneficiary_2008.head()

,DESYNPUF_ID,BENE_BIRTH_DT,BENE_DEATH_DT,BENE_SEX_IDENT_CD,BENE_RACE_CD,BENE_ESRD_IND,SP_STATE_CODE,BENE_COUNTY_CD,BENE_HI_CVRAGE_TOT_MONS,BENE_SMI_CVRAGE_TOT_MONS,...,SP_STRKETIA,MEDREIMB_IP,BENRES_IP,PPPYMT_IP,MEDREIMB_OP,BENRES_OP,PPPYMT_OP,MEDREIMB_CAR,BENRES_CAR,PPPYMT_CAR
0,00013D2EFD8E45D1,19230501,NaN,1,1,0,26,950,12,12,...,2,0.0,0.0,0.0,50.0,10.0,0.0,0.0,0.0,0.0
1,00016F745862898F,19430101,NaN,1,1,0,39,230,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,700.0,240.0,0.0
2,0001FDD721E223DC,19360901,NaN,2,1,0,39,280,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,00021CA6FF03E670,19410601,NaN,1,5,0,6,290,0,0,...,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,00024B3D2352D2D0,19360801,NaN,1,1,0,52,590,12,12,...,2,0.0,0.0,0.0,30.0,40.0,0.0,220.0,80.0,0.0

In [4]:
beneficiary_2009.head()

,DESYNPUF_ID,BENE_BIRTH_DT,BENE_DEATH_DT,BENE_SEX_IDENT_CD,BENE_RACE_CD,BENE_ESRD_IND,SP_STATE_CODE,BENE_COUNTY_CD,BENE_HI_CVRAGE_TOT_MONS,BENE_SMI_CVRAGE_TOT_MONS,...,SP_STRKETIA,MEDREIMB_IP,BENRES_IP,PPPYMT_IP,MEDREIMB_OP,BENRES_OP,PPPYMT_OP,MEDREIMB_CAR,BENRES_CAR,PPPYMT_CAR
0,00013D2EFD8E45D1,19230501,NaN,1,1,0,26,950,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,100.0,20.0,0.0
1,00016F745862898F,19430101,NaN,1,1,0,39,230,12,12,...,1,36000.0,3204.0,0.0,60.0,70.0,0.0,1350.0,530.0,100.0
2,0001FDD721E223DC,19360901,NaN,2,1,0,39,280,12,12,...,2,0.0,0.0,0.0,30.0,50.0,0.0,20.0,0.0,0.0
3,00021CA6FF03E670,19410601,NaN,1,5,0,6,290,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,90.0,10.0,0.0
4,00024B3D2352D2D0,19360801,NaN,1,1,0,52,590,12,12,...,2,0.0,0.0,0.0,90.0,40.0,0.0,410.0,140.0,0.0

In [5]:
beneficiary_2010.head()

,Beneficiory_ID,DOB,Date of Death,SEX,RACE,End-Stage Renal Disease indicator,STATE,COUNTY,Part A (Hospital insurance),Part B (Medical insurance),...,SP_STRKETIA,Medicare PaidAmount_IP,BENRES_IP,PPPYMT_IP,MEDREIMB_OP,BENRES_OP,PPPYMT_OP,MEDREIMB_CAR,BENRES_CAR,PPPYMT_CAR
0,00013D2EFD8E45D1,19230501,NaN,1,1,0,26,950,12,12,...,2,4000,1100,0,0,0,0,90,30,0
1,00016F745862898F,19430101,NaN,1,1,Y,39,230,12,12,...,2,16000,1100,0,0,0,0,930,150,0
2,0001FDD721E223DC,19360901,NaN,2,1,0,39,280,12,12,...,2,0,0,0,0,0,0,0,0,0
3,00021CA6FF03E670,19410601,NaN,1,5,0,6,290,12,12,...,2,0,0,0,0,0,0,0,0,0
4,00024B3D2352D2D0,19360801,NaN,1,1,0,52,590,9,12,...,2,0,0,0,40,0,0,590,60,0

In [6]:
inpatient.head()

,DESYNPUF_ID,CLM_ID,SEGMENT,CLM_FROM_DT,CLM_THRU_DT,PRVDR_NUM,CLM_PMT_AMT,NCH_PRMRY_PYR_CLM_PD_AMT,AT_PHYSN_NPI,OP_PHYSN_NPI,...,HCPCS_CD_36,HCPCS_CD_37,HCPCS_CD_38,HCPCS_CD_39,HCPCS_CD_40,HCPCS_CD_41,HCPCS_CD_42,HCPCS_CD_43,HCPCS_CD_44,HCPCS_CD_45
0,00013D2EFD8E45D1,196661176988405,1,20100312.0,20100313.0,2600GD,4000.0,0.0,3.139084e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00016F745862898F,196201177000368,1,20090412.0,20090418.0,3900MB,26000.0,0.0,6.476809e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00016F745862898F,196661177015632,1,20090831.0,20090902.0,3900HM,5000.0,0.0,6.119985e+08,6.119985e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,00016F745862898F,196091176981058,1,20090917.0,20090920.0,3913XU,5000.0,0.0,4.971603e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00016F745862898F,196261176983265,1,20100626.0,20100701.0,3900MB,16000.0,0.0,6.408400e+09,1.960860e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
outpatient.head()

,DESYNPUF_ID,CLM_ID,SEGMENT,CLM_FROM_DT,CLM_THRU_DT,PRVDR_NUM,CLM_PMT_AMT,NCH_PRMRY_PYR_CLM_PD_AMT,AT_PHYSN_NPI,OP_PHYSN_NPI,...,HCPCS_CD_36,HCPCS_CD_37,HCPCS_CD_38,HCPCS_CD_39,HCPCS_CD_40,HCPCS_CD_41,HCPCS_CD_42,HCPCS_CD_43,HCPCS_CD_44,HCPCS_CD_45
0,00013D2EFD8E45D1,542192281063886,1,20080904,20080904,2600RA,50.00,0.00,4824842417,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,00016F745862898F,542272281166593,1,20090602,20090602,3901GS,30.00,0.00,2963419753,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,00016F745862898F,542282281644416,1,20090623,20090623,3939PG,30.00,0.00,5737807753,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,0001FDD721E223DC,542642281250669,1,20091011,20091011,3902NU,30.00,0.00,1233847710,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,00024B3D2352D2D0,542242281386963,1,20080712,20080712,5200TV,30.00,0.00,9688809345,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [8]:
beneficiary_2008.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116352 entries, 0 to 116351
Data columns (total 32 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   DESYNPUF_ID               116352 non-null  object
 1   BENE_BIRTH_DT             116352 non-null  int64
 2   BENE_DEATH_DT             1814 non-null    float64
 3   BENE_SEX_IDENT_CD         116352 non-null  int64
 4   BENE_RACE_CD              116352 non-null  int64
 5   BENE_ESRD_IND             116352 non-null  object
 6   SP_STATE_CODE             116352 non-null  int64
 7   BENE_COUNTY_CD            116352 non-null  int64
 8   BENE_HI_CVRAGE_TOT_MONS   116352 non-null  int64
 9   BENE_SMI_CVRAGE_TOT_MONS  116352 non-null  int64
 10  BENE_HMO_CVRAGE_TOT_MONS  116352 non-null  int64
 11  PLAN_CVRG_MOS_NUM         116352 non-null  int64
 12  SP_ALZHDMTA               116352 non-null  int64
 13  SP_CHF                    116352 non-null  int64
 14  SP_CHRNKIDN               116352 non-null  int64
 15  SP_CNCR                   116352 non-null  int64
 16  SP_COPD                   116352 non-null  int64
 17  SP_DEPRESSN               116352 non-null  int64
 18  SP_DIABETES               116352 non-null  int64
 19  SP_ISCHMCHT               116352 non-null  int64
 20  SP_OSTEOPRS               116352 non-null  int64
 21  SP_RA_OA                  116352 non-null  int64
 22  SP_STRKETIA               116352 non-null  int64
 23  MEDREIMB_IP               116352 non-null  float64
 24  BENRES_IP                 116352 non-null  float64
 25  PPPYMT_IP                 116352 non-null  float64
 26  MEDREIMB_OP               116352 non-null  float64
 27  BENRES_OP                 116352 non-null  float64
 28  PPPYMT_OP                 116352 non-null  float64
 29  MEDREIMB_CAR              116352 non-null  float64
 30  BENRES_CAR                116352 non-null  float64
 31  PPPYMT_CAR                116352 non-null  float64
dtypes: float64(10), int64(20), object(2)
memory usage: 28.4+ MB

In [9]:
beneficiary_2009.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114538 entries, 0 to 114537
Data columns (total 32 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   DESYNPUF_ID               114538 non-null  object
 1   BENE_BIRTH_DT             114538 non-null  int64
 2   BENE_DEATH_DT             1784 non-null    float64
 3   BENE_SEX_IDENT_CD         114538 non-null  int64
 4   BENE_RACE_CD              114538 non-null  int64
 5   BENE_ESRD_IND             114538 non-null  object
 6   SP_STATE_CODE             114538 non-null  int64
 7   BENE_COUNTY_CD            114538 non-null  int64
 8   BENE_HI_CVRAGE_TOT_MONS   114538 non-null  int64
 9   BENE_SMI_CVRAGE_TOT_MONS  114538 non-null  int64
 10  BENE_HMO_CVRAGE_TOT_MONS  114538 non-null  int64
 11  PLAN_CVRG_MOS_NUM         114538 non-null  int64
 12  SP_ALZHDMTA               114538 non-null  int64
 13  SP_CHF                    114538 non-null  int64
 14  SP_CHRNKIDN               114538 non-null  int64
 15  SP_CNCR                   114538 non-null  int64
 16  SP_COPD                   114538 non-null  int64
 17  SP_DEPRESSN               114538 non-null  int64
 18  SP_DIABETES               114538 non-null  int64
 19  SP_ISCHMCHT               114538 non-null  int64
 20  SP_OSTEOPRS               114538 non-null  int64
 21  SP_RA_OA                  114538 non-null  int64
 22  SP_STRKETIA               114538 non-null  int64
 23  MEDREIMB_IP               114538 non-null  float64
 24  BENRES_IP                 114538 non-null  float64
 25  PPPYMT_IP                 114538 non-null  float64
 26  MEDREIMB_OP               114538 non-null  float64
 27  BENRES_OP                 114538 non-null  float64
 28  PPPYMT_OP                 114538 non-null  float64
 29  MEDREIMB_CAR              114538 non-null  float64
 30  BENRES_CAR                114538 non-null  float64
 31  PPPYMT_CAR                114538 non-null  float64
dtypes: float64(10), int64(20), object(2)
memory usage: 28.0+ MB

In [10]:
beneficiary_2010.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112754 entries, 0 to 112753
Data columns (total 32 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Beneficiory_ID                      112754 non-null  object
 1   DOB                                 112754 non-null  int64
 2   Date of Death                       1863 non-null    float64
 3   SEX                                 112754 non-null  int64
 4   RACE                                112754 non-null  int64
 5   End-Stage Renal Disease indicator   112754 non-null  object
 6   STATE                               112754 non-null  int64
 7   COUNTY                              112754 non-null  int64
 8    Part A (Hospital insurance)        112754 non-null  int64
 9   Part B (Medical insurance)          112754 non-null  int64
 10  HMO                                 112754 non-null  int64
 11  Total months of any plan coverage   112754 non-null  int64
 12  SP_ALZHDMTA                         112754 non-null  int64
 13  SP_CHF                              112754 non-null  int64
 14  SP_CHRNKIDN                         112754 non-null  int64
 15  SP_CNCR                             112754 non-null  int64
 16  SP_COPD                             112754 non-null  int64
 17  SP_DEPRESSN                         112754 non-null  int64
 18  SP_DIABETES                         112754 non-null  int64
 19  SP_ISCHMCHT                         112754 non-null  int64
 20  SP_OSTEOPRS                         112754 non-null  int64
 21  SP_RA_OA                            112754 non-null  int64
 22  SP_STRKETIA                         112754 non-null  int64
 23  Medicare PaidAmount_IP              112754 non-null  int64
 24  BENRES_IP                           112754 non-null  int64
 25  PPPYMT_IP                           112754 non-null  int64
 26  MEDREIMB_OP                         112754 non-null  int64
 27  BENRES_OP                           112754 non-null  int64
 28  PPPYMT_OP                           112754 non-null  int64
 29  MEDREIMB_CAR                        112754 non-null  int64
 30  BENRES_CAR                          112754 non-null  int64
 31  PPPYMT_CAR                          112754 non-null  int64
dtypes: float64(1), int64(29), object(2)
memory usage: 27.5+ MB

In [11]:
inpatient.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66773 entries, 0 to 66772
Data columns (total 81 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   DESYNPUF_ID                     66773 non-null  object
 1   CLM_ID                          66773 non-null  int64
 2   SEGMENT                         66773 non-null  int64
 3   CLM_FROM_DT                     66705 non-null  float64
 4   CLM_THRU_DT                     66705 non-null  float64
 5   PRVDR_NUM                       66773 non-null  object
 6   CLM_PMT_AMT                     66773 non-null  float64
 7   NCH_PRMRY_PYR_CLM_PD_AMT        66773 non-null  float64
 8   AT_PHYSN_NPI                    66100 non-null  float64
 9   OP_PHYSN_NPI                    39058 non-null  float64
 10  OT_PHYSN_NPI                    7683 non-null   float64
 11  CLM_ADMSN_DT                    66773 non-null  int64
 12  ADMTNG_ICD9_DGNS_CD             66174 non-null  object
 13  CLM_PASS_THRU_PER_DIEM_AMT      66773 non-null  float64
 14  NCH_BENE_IP_DDCTBL_AMT          64595 non-null  float64
 15  NCH_BENE_PTA_COINSRNC_LBLTY_AM  66773 non-null  float64
 16  NCH_BENE_BLOOD_DDCTBL_LBLTY_AM  66773 non-null  float64
 17  CLM_UTLZTN_DAY_CNT              66705 non-null  float64
 18  NCH_BENE_DSCHRG_DT              66773 non-null  int64
 19  CLM_DRG_CD                      66773 non-null  object
 20  ICD9_DGNS_CD_1                  66678 non-null  object
 21  ICD9_DGNS_CD_2                  66247 non-null  object
 22  ICD9_DGNS_CD_3                  65492 non-null  object
 23  ICD9_DGNS_CD_4                  64005 non-null  object
 24  ICD9_DGNS_CD_5                  61639 non-null  object
 25  ICD9_DGNS_CD_6                  58369 non-null  object
 26  ICD9_DGNS_CD_7                  54407 non-null  object
 27  ICD9_DGNS_CD_8                  49947 non-null  object
 28  ICD9_DGNS_CD_9                  45032 non-null  object
 29  ICD9_DGNS_CD_10                 5455 non-null   object
 30  ICD9_PRCDR_CD_1                 38231 non-null  float64
 31  ICD9_PRCDR_CD_2                 22733 non-null  object
 32  ICD9_PRCDR_CD_3                 14462 non-null  object
 33  ICD9_PRCDR_CD_4                 9377 non-null   object
 34  ICD9_PRCDR_CD_5                 6446 non-null   object
 35  ICD9_PRCDR_CD_6                 4622 non-null   object
 36  HCPCS_CD_1                      0 non-null      float64
 37  HCPCS_CD_2                      0 non-null      float64
 38  HCPCS_CD_3                      0 non-null      float64
 39  HCPCS_CD_4                      0 non-null      float64
 40  HCPCS_CD_5                      0 non-null      float64
 41  HCPCS_CD_6                      0 non-null      float64
 42  HCPCS_CD_7                      0 non-null      float64
 43  HCPCS_CD_8                      0 non-null      float64
 44  HCPCS_CD_9                      0 non-null      float64
 45  HCPCS_CD_10                     0 non-null      float64
 46  HCPCS_CD_11                     0 non-null      float64
 47  HCPCS_CD_12                     0 non-null      float64
 48  HCPCS_CD_13                     0 non-null      float64
 49  HCPCS_CD_14                     0 non-null      float64
 50  HCPCS_CD_15                     0 non-null      float64
 51  HCPCS_CD_16                     0 non-null      float64
 52  HCPCS_CD_17                     0 non-null      float64
 53  HCPCS_CD_18                     0 non-null      float64
 54  HCPCS_CD_19                     0 non-null      float64
 55  HCPCS_CD_20                     0 non-null      float64
 56  HCPCS_CD_21                     0 non-null      float64
 57  HCPCS_CD_22                     0 non-null      float64
 58  HCPCS_CD_23                     0 non-null      float64
 59  HCPCS_CD_24                     0 non-null      float64
 60  HCPCS_CD_25                     0 non-null      float64
 61  HCPCS_CD_26                     0 non-null      float64
 62  HCPCS_CD_27                     0 non-null      float64
 63  HCPCS_CD_28                     0 non-null      float64
 64  HCPCS_CD_29                     0 non-null      float64
 65  HCPCS_CD_30                     0 non-null      float64
 66  HCPCS_CD_31                     0 non-null      float64
 67  HCPCS_CD_32                     0 non-null      float64
 68  HCPCS_CD_33                     0 non-null      float64
 69  HCPCS_CD_34                     0 non-null      float64
 70  HCPCS_CD_35                     0 non-null      float64
 71  HCPCS_CD_36                     0 non-null      float64
 72  HCPCS_CD_37                     0 non-null      float64
 73  HCPCS_CD_38                     0 non-null      float64
 74  HCPCS_CD_39                     0 non-null      float64
 75  HCPCS_CD_40                     0 non-null      float64
 76  HCPCS_CD_41                     0 non-null      float64
 77  HCPCS_CD_42                     0 non-null      float64
 78  HCPCS_CD_43                     0 non-null      float64
 79  HCPCS_CD_44                     0 non-null      float64
 80  HCPCS_CD_45                     0 non-null      float64
dtypes: float64(58), int64(4), object(19)
memory usage: 41.3+ MB

In [12]:
outpatient.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 790790 entries, 0 to 790789
Data columns (total 76 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   DESYNPUF_ID                     790790 non-null  string
 1   CLM_ID                          790790 non-null  string
 2   SEGMENT                         790790 non-null  string
 3   CLM_FROM_DT                     779537 non-null  string
 4   CLM_THRU_DT                     779537 non-null  string
 5   PRVDR_NUM                       790790 non-null  string
 6   CLM_PMT_AMT                     790790 non-null  string
 7   NCH_PRMRY_PYR_CLM_PD_AMT        790790 non-null  string
 8   AT_PHYSN_NPI                    773000 non-null  string
 9   OP_PHYSN_NPI                    134433 non-null  string
 10  OT_PHYSN_NPI                    257666 non-null  string
 11  NCH_BENE_BLOOD_DDCTBL_LBLTY_AM  790790 non-null  string
 12  ICD9_DGNS_CD_1                  785170 non-null  string
 13  ICD9_DGNS_CD_2                  492433 non-null  string
 14  ICD9_DGNS_CD_3                  310937 non-null  string
 15  ICD9_DGNS_CD_4                  191642 non-null  string
 16  ICD9_DGNS_CD_5                  112150 non-null  string
 17  ICD9_DGNS_CD_6                  72876 non-null   string
 18  ICD9_DGNS_CD_7                  49146 non-null   string
 19  ICD9_DGNS_CD_8                  34142 non-null   string
 20  ICD9_DGNS_CD_9                  23675 non-null   string
 21  ICD9_DGNS_CD_10                 1625 non-null    string
 22  ICD9_PRCDR_CD_1                 200 non-null     string
 23  ICD9_PRCDR_CD_2                 123 non-null     string
 24  ICD9_PRCDR_CD_3                 73 non-null      string
 25  ICD9_PRCDR_CD_4                 48 non-null      string
 26  ICD9_PRCDR_CD_5                 35 non-null      string
 27  ICD9_PRCDR_CD_6                 29 non-null      string
 28  NCH_BENE_PTB_DDCTBL_AMT         790790 non-null  string
 29  NCH_BENE_PTB_COINSRNC_AMT       790790 non-null  string
 30  ADMTNG_ICD9_DGNS_CD             194486 non-null  string
 31  HCPCS_CD_1                      646260 non-null  string
 32  HCPCS_CD_2                      451369 non-null  string
 33  HCPCS_CD_3                      331508 non-null  string
 34  HCPCS_CD_4                      273257 non-null  string
 35  HCPCS_CD_5                      226269 non-null  string
 36  HCPCS_CD_6                      190088 non-null  string
 37  HCPCS_CD_7                      160249 non-null  string
 38  HCPCS_CD_8                      137593 non-null  string
 39  HCPCS_CD_9                      119791 non-null  string
 40  HCPCS_CD_10                     105504 non-null  string
 41  HCPCS_CD_11                     93609 non-null   string
 42  HCPCS_CD_12                     83909 non-null   string
 43  HCPCS_CD_13                     75011 non-null   string
 44  HCPCS_CD_14                     67864 non-null   string
 45  HCPCS_CD_15                     61748 non-null   string
 46  HCPCS_CD_16                     56297 non-null   string
 47  HCPCS_CD_17                     51470 non-null   string
 48  HCPCS_CD_18                     47291 non-null   string
 49  HCPCS_CD_19                     43684 non-null   string
 50  HCPCS_CD_20                     40353 non-null   string
 51  HCPCS_CD_21                     37472 non-null   string
 52  HCPCS_CD_22                     35049 non-null   string
 53  HCPCS_CD_23                     32971 non-null   string
 54  HCPCS_CD_24                     31118 non-null   string
 55  HCPCS_CD_25                     29291 non-null   string
 56  HCPCS_CD_26                     27810 non-null   string
 57  HCPCS_CD_27                     26542 non-null   string
 58  HCPCS_CD_28                     25127 non-null   string
 59  HCPCS_CD_29                     23934 non-null   string
 60  HCPCS_CD_30                     22767 non-null   string
 61  HCPCS_CD_31                     21499 non-null   string
 62  HCPCS_CD_32                     20375 non-null   string
 63  HCPCS_CD_33                     19366 non-null   string
 64  HCPCS_CD_34                     18377 non-null   string
 65  HCPCS_CD_35                     17516 non-null   string
 66  HCPCS_CD_36                     16748 non-null   string
 67  HCPCS_CD_37                     15940 non-null   string
 68  HCPCS_CD_38                     15126 non-null   string
 69  HCPCS_CD_39                     14399 non-null   string
 70  HCPCS_CD_40                     13492 non-null   string
 71  HCPCS_CD_41                     12668 non-null   string
 72  HCPCS_CD_42                     11876 non-null   string
 73  HCPCS_CD_43                     11196 non-null   string
 74  HCPCS_CD_44                     10556 non-null   string
 75  HCPCS_CD_45                     0 non-null       string
dtypes: string(76)
memory usage: 458.5 MB

In [5]:
import pandas as pd

COLUMN_RENAME_MAP = {
    # IDs
    "BENEFICIARY_ID": "beneficiary_id",
    "DESYNPUF_ID": "beneficiary_id",
    "Beneficiory_ID": "beneficiary_id",  # 2010 labelled (typo)

    # Dates
    "BENE_BIRTH_DT": "birth_date",
    "DOB": "birth_date",
    "BENE_DEATH_DT": "death_date",
    "Date of Death": "death_date",

    # Demographics
    "BENE_SEX_IDENT_CD": "sex_code",
    "SEX": "sex_code",
    "BENE_RACE_CD": "race_code",
    "RACE": "race_code",

    # ESRD
    "BENE_ESRD_IND": "esrd_indicator",
    "End-Stage Renal Disease indicator": "esrd_indicator",

    # Geography
    "SP_STATE_CODE": "state_code",
    "STATE": "state_code",
    "BENE_COUNTY_CD": "county_code",
    "COUNTY": "county_code",

    # Coverage
    "BENE_HI_CVRAGE_TOT_MONS": "part_a_coverage_months",
    "Part A (Hospital insurance)": "part_a_coverage_months",
    "BENE_SMI_CVRAGE_TOT_MONS": "part_b_coverage_months",
    "Part B (Medical insurance)": "part_b_coverage_months",
    "BENE_HMO_CVRAGE_TOT_MONS": "hmo_coverage_months",
    "HMO": "hmo_coverage_months",
    "PLAN_CVRG_MOS_NUM": "total_coverage_months",
    "Total months of any plan coverage": "total_coverage_months",

    # Chronic flags
    "SP_ALZHDMTA": "chronic_alzheimer",
    "SP_CHF": "chronic_heart_failure",
    "SP_CHRNKIDN": "chronic_kidney_disease",
    "SP_CNCR": "chronic_cancer",
    "SP_COPD": "chronic_copd",
    "SP_DEPRESSN": "chronic_depression",
    "SP_DIABETES": "chronic_diabetes",
    "SP_ISCHMCHT": "chronic_ischemic_heart_disease",
    "SP_OSTEOPRS": "chronic_osteoporosis",
    "SP_RA_OA": "chronic_rheumatoid_arthritis_osteoarthritis",
    "SP_STRKETIA": "chronic_stroke_tia",

    # Payments
    "MEDREIMB_IP": "medicare_payment_inpatient",
    "Medicare PaidAmount_IP": "medicare_payment_inpatient",
    "BENRES_IP": "beneficiary_payment_inpatient",
    "PPPYMT_IP": "third_party_payment_inpatient",

    "MEDREIMB_OP": "medicare_payment_outpatient",
    "BENRES_OP": "beneficiary_payment_outpatient",
    "PPPYMT_OP": "third_party_payment_outpatient",

    "MEDREIMB_CAR": "medicare_payment_carrier",
    "BENRES_CAR": "beneficiary_payment_carrier",
    "PPPYMT_CAR": "third_party_payment_carrier",
}

# Only raw chronic columns need conversion (labelled file already has chronic_* booleans)
CHRONIC_RAW_COLS = [
    "SP_ALZHDMTA", "SP_CHF", "SP_CHRNKIDN", "SP_CNCR", "SP_COPD",
    "SP_DEPRESSN", "SP_DIABETES", "SP_ISCHMCHT", "SP_OSTEOPRS",
    "SP_RA_OA", "SP_STRKETIA"
]


def prepare_beneficiary_year(
    df: pd.DataFrame,
    year: int,
    add_features: bool = True,
    date_format: str = "%Y%m%d",
) -> pd.DataFrame:
    """
    Clean + standardise a DE-SynPUF beneficiary dataframe for a given year.
    Handles both CMS raw uppercase columns and 2010 labelled/human-readable columns.
    """
    df = df.copy()

    # 0) Normalise column whitespace (critical for ' Part A ...')
    df.columns = df.columns.astype(str).str.strip()

    # 1) Convert chronic flags if raw cols exist (SP_* only)
    present_chronic = [c for c in CHRONIC_RAW_COLS if c in df.columns]
    for c in present_chronic:
        df[c] = pd.to_numeric(df[c], errors="coerce").eq(1).astype("boolean")

    # 2) ESRD: handle both raw and labelled variants BEFORE rename
    if "BENE_ESRD_IND" in df.columns:
        s = df["BENE_ESRD_IND"]
        if s.dtype == "object":
            df["BENE_ESRD_IND"] = s.replace({"Y": 1, "N": 0}).fillna(0).astype(int)
        else:
            df["BENE_ESRD_IND"] = pd.to_numeric(s, errors="coerce").fillna(0).astype(int)

    if "End-Stage Renal Disease indicator" in df.columns:
        s = df["End-Stage Renal Disease indicator"]
        if s.dtype == "object":
            df["End-Stage Renal Disease indicator"] = s.replace({"Y": 1, "N": 0}).fillna(0).astype(int)
        else:
            df["End-Stage Renal Disease indicator"] = pd.to_numeric(s, errors="coerce").fillna(0).astype(int)

    # 3) Rename columns to canonical names
    rename_map_present = {k: v for k, v in COLUMN_RENAME_MAP.items() if k in df.columns}
    df = df.rename(columns=rename_map_present)

    # 4) Parse dates AFTER rename (so both raw and labelled become birth_date/death_date)
    if "birth_date" in df.columns:
        # if it's numeric yyyymmdd, parse with format; otherwise let pandas infer
        if pd.api.types.is_numeric_dtype(df["birth_date"]):
            df["birth_date"] = pd.to_datetime(df["birth_date"].astype("Int64").astype(str), format=date_format, errors="coerce")
        else:
            df["birth_date"] = pd.to_datetime(df["birth_date"], errors="coerce")

    if "death_date" in df.columns:
        if pd.api.types.is_numeric_dtype(df["death_date"]):
            df["death_date"] = pd.to_datetime(df["death_date"].astype("Int64").astype(str), format=date_format, errors="coerce")
        else:
            df["death_date"] = pd.to_datetime(df["death_date"], errors="coerce")

    # 5) Add derived features
    if add_features:
        df["year"] = year

        # Use age_at_year instead of age (dimension-friendly)
        if "birth_date" in df.columns:
            df["age_at_year"] = (year - df["birth_date"].dt.year).astype("Int64")

        # Alive flag at end of that year
        if "death_date" in df.columns:
            df["is_alive_flag"] = df["death_date"].isna() | (df["death_date"].dt.year > year)
        else:
            df["is_alive_flag"] = pd.Series([True] * len(df), dtype="boolean")

        chronic_cols = [c for c in df.columns if c.startswith("chronic_")]
        if chronic_cols and "chronic_condition_count" not in df.columns:
            df["chronic_condition_count"] = df[chronic_cols].sum(axis=1)

        # Totals (I still think these should move to FACT later, but keeping your current design)
        if df.filter(like="medicare_payment_").shape[1] > 0:
            df["total_medicare_payment"] = df.filter(like="medicare_payment_").sum(axis=1)
        if df.filter(like="beneficiary_payment_").shape[1] > 0:
            df["total_beneficiary_payment"] = df.filter(like="beneficiary_payment_").sum(axis=1)
        if df.filter(like="third_party_payment_").shape[1] > 0:
            df["total_third_party_payment"] = df.filter(like="third_party_payment_").sum(axis=1)

        if {"total_medicare_payment", "total_beneficiary_payment", "total_third_party_payment"}.issubset(df.columns):
            df["total_payment"] = (
                df["total_medicare_payment"]
                + df["total_beneficiary_payment"]
                + df["total_third_party_payment"]
            )

    return df

In [6]:
beneficiary_2008_clean = prepare_beneficiary_year(beneficiary_2008, 2008)
beneficiary_2009_clean = prepare_beneficiary_year(beneficiary_2009, 2009)
beneficiary_2010_clean = prepare_beneficiary_year(beneficiary_2010, 2010)

In [7]:
beneficiary_all = pd.concat(
    [beneficiary_2008_clean, beneficiary_2009_clean, beneficiary_2010_clean],
    ignore_index=True
)

In [9]:
beneficiary_all.to_csv(
    "stg_beneficiary_all_clean.csv",
    index=False
)

In [28]:
beneficiary_all.dtypes

beneficiary_id                                         object
birth_date                                     datetime64[ns]
death_date                                     datetime64[ns]
sex_code                                                int64
race_code                                               int64
esrd_indicator                                          int32
state_code                                              int64
county_code                                             int64
part_a_coverage_months                                  int64
part_b_coverage_months                                  int64
hmo_coverage_months                                     int64
total_coverage_months                                   int64
chronic_alzheimer                                     boolean
chronic_heart_failure                                 boolean
chronic_kidney_disease                                boolean
chronic_cancer                                        boolean
chronic_copd                                          boolean
chronic_depression                                    boolean
chronic_diabetes                                      boolean
chronic_ischemic_heart_disease                        boolean
chronic_osteoporosis                                  boolean
chronic_rheumatoid_arthritis_osteoarthritis           boolean
chronic_stroke_tia                                    boolean
medicare_payment_inpatient                            float64
beneficiary_payment_inpatient                         float64
third_party_payment_inpatient                         float64
medicare_payment_outpatient                           float64
beneficiary_payment_outpatient                        float64
third_party_payment_outpatient                        float64
medicare_payment_carrier                              float64
beneficiary_payment_carrier                           float64
third_party_payment_carrier                           float64
year                                                    int64
age_at_year                                             Int64
is_alive_flag                                            bool
chronic_condition_count                                 int32
total_medicare_payment                                float64
total_beneficiary_payment                             float64
total_third_party_payment                             float64
total_payment                                         float64
dtype: object

In [3]:
import pandas as pd
from typing import Optional

# ---------- Configuration ----------
INPATIENT_RENAME_MAP = {
    "DESYNPUF_ID": "beneficiary_id",
    "CLM_ID": "claim_id",
    "PRVDR_NUM": "provider_id",

    "CLM_FROM_DT": "claim_start_date",
    "CLM_THRU_DT": "claim_end_date",
    "CLM_ADMSN_DT": "admission_date",
    "NCH_BENE_DSCHRG_DT": "discharge_date",

    "CLM_PMT_AMT": "medicare_payment_amount",
    "NCH_PRMRY_PYR_CLM_PD_AMT": "primary_payer_paid_amount",

    "CLM_UTLZTN_DAY_CNT": "utilization_days",
    "CLM_DRG_CD": "drg_code",

    "ADMTNG_ICD9_DGNS_CD": "primary_diagnosis",
}

DATE_COLS = ["claim_start_date", "claim_end_date", "admission_date", "discharge_date"]

NUMERIC_COLS = [
    "medicare_payment_amount",
    "primary_payer_paid_amount",
    "utilization_days",
]

REQUIRED_COLS = ["beneficiary_id", "claim_id", "admission_date", "discharge_date"]


def _parse_yyyymmdd(series: pd.Series, fmt: str = "%Y%m%d") -> pd.Series:
    """Parse yyyymmdd dates stored as int/float/str."""
    s = series.copy()
    if pd.api.types.is_numeric_dtype(s):
        s = s.astype("Int64").astype(str)
    else:
        s = s.astype(str).str.strip()
    return pd.to_datetime(s, format=fmt, errors="coerce")


def clean_inpatient_claims(
    df: pd.DataFrame,
    year_hint: Optional[int] = None,
    date_format: str = "%Y%m%d",
    keep_optional_code_columns: bool = True,
) -> pd.DataFrame:
    """
    Clean + standardise DE-SynPUF inpatient claims at claim-grain (1 row = 1 claim).
    Produces a staging dataframe suitable for loading to SQL as stg_inpatient_claims.
    """
    df = df.copy()

    # 0) Normalize headers
    df.columns = df.columns.astype(str).str.strip()

    # 1) Rename columns (only those present)
    rename_present = {k: v for k, v in INPATIENT_RENAME_MAP.items() if k in df.columns}
    df = df.rename(columns=rename_present)

    # 2) Parse dates
    for c in DATE_COLS:
        if c in df.columns:
            df[c] = _parse_yyyymmdd(df[c], fmt=date_format)

    # 3) Clean numerics
    for c in NUMERIC_COLS:
        if c in df.columns:
            df[c] = pd.to_numeric(df[c], errors="coerce")

    # 4) Strip ids/codes
    for c in ["beneficiary_id", "claim_id", "provider_id", "drg_code", "primary_diagnosis"]:
        if c in df.columns:
            df[c] = df[c].astype(str).str.strip().replace({"": pd.NA})

    # 5) Drop bad rows missing required fields
    present_required = [c for c in REQUIRED_COLS if c in df.columns]
    if present_required:
        df = df.dropna(subset=present_required).copy()

    # 6) Derive length_of_stay
    df["length_of_stay"] = (df["discharge_date"] - df["admission_date"]).dt.days
    df.loc[df["length_of_stay"] < 0, "length_of_stay"] = pd.NA

    # 7) Derive year (use admission_date year)
    df["year"] = df["admission_date"].dt.year.astype("Int64")
    if df["year"].isna().all() and year_hint is not None:
        df["year"] = pd.Series([year_hint] * len(df), dtype="Int64")

    # 8) Claim grain check: remove duplicates by claim_id
    if "claim_id" in df.columns:
        dup_mask = df["claim_id"].duplicated(keep="first")
        df["claim_id_duplicated_flag"] = dup_mask
        df = df[~dup_mask].copy()

    # 9) Optional: clean wide code columns (keep them, but strip whitespace)
    if keep_optional_code_columns:
        code_prefixes = ("ICD9_DGNS_CD_", "ICD9_PRCDR_CD_", "HCPCS_CD_")
        for c in df.columns:
            if c.startswith(code_prefixes):
                df[c] = df[c].astype(str).str.strip().replace({"": pd.NA, "nan": pd.NA, "None": pd.NA})

    # 10) Order core columns first
    core_order = [
        "claim_id",
        "beneficiary_id",
        "provider_id",
        "admission_date",
        "discharge_date",
        "claim_start_date",
        "claim_end_date",
        "year",
        "length_of_stay",
        "utilization_days",
        "drg_code",
        "primary_diagnosis",
        "medicare_payment_amount",
        "primary_payer_paid_amount",
        "claim_id_duplicated_flag",
    ]
    existing_core = [c for c in core_order if c in df.columns]
    remaining = [c for c in df.columns if c not in existing_core]
    return df[existing_core + remaining]

In [6]:
inpatient_clean = clean_inpatient_claims(inpatient)

In [7]:
inpatient_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 66705 entries, 0 to 66772
Data columns (total 84 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   claim_id                        66705 non-null  object
 1   beneficiary_id                  66705 non-null  object
 2   provider_id                     66705 non-null  object
 3   admission_date                  66705 non-null  datetime64[ns]
 4   discharge_date                  66705 non-null  datetime64[ns]
 5   claim_start_date                66637 non-null  datetime64[ns]
 6   claim_end_date                  66637 non-null  datetime64[ns]
 7   year                            66705 non-null  Int64
 8   length_of_stay                  66705 non-null  float64
 9   utilization_days                66637 non-null  float64
 10  drg_code                        66705 non-null  object
 11  primary_diagnosis               66705 non-null  object
 12  medicare_payment_amount         66705 non-null  float64
 13  primary_payer_paid_amount       66705 non-null  float64
 14  claim_id_duplicated_flag        66705 non-null  bool
 15  SEGMENT                         66705 non-null  int64
 16  AT_PHYSN_NPI                    66037 non-null  float64
 17  OP_PHYSN_NPI                    39003 non-null  float64
 18  OT_PHYSN_NPI                    7676 non-null   float64
 19  CLM_PASS_THRU_PER_DIEM_AMT      66705 non-null  float64
 20  NCH_BENE_IP_DDCTBL_AMT          64533 non-null  float64
 21  NCH_BENE_PTA_COINSRNC_LBLTY_AM  66705 non-null  float64
 22  NCH_BENE_BLOOD_DDCTBL_LBLTY_AM  66705 non-null  float64
 23  ICD9_DGNS_CD_1                  66610 non-null  object
 24  ICD9_DGNS_CD_2                  66179 non-null  object
 25  ICD9_DGNS_CD_3                  65425 non-null  object
 26  ICD9_DGNS_CD_4                  63937 non-null  object
 27  ICD9_DGNS_CD_5                  61572 non-null  object
 28  ICD9_DGNS_CD_6                  58301 non-null  object
 29  ICD9_DGNS_CD_7                  54340 non-null  object
 30  ICD9_DGNS_CD_8                  49883 non-null  object
 31  ICD9_DGNS_CD_9                  44971 non-null  object
 32  ICD9_DGNS_CD_10                 5437 non-null   object
 33  ICD9_PRCDR_CD_1                 38171 non-null  object
 34  ICD9_PRCDR_CD_2                 22681 non-null  object
 35  ICD9_PRCDR_CD_3                 14420 non-null  object
 36  ICD9_PRCDR_CD_4                 9347 non-null   object
 37  ICD9_PRCDR_CD_5                 6418 non-null   object
 38  ICD9_PRCDR_CD_6                 4600 non-null   object
 39  HCPCS_CD_1                      0 non-null      object
 40  HCPCS_CD_2                      0 non-null      object
 41  HCPCS_CD_3                      0 non-null      object
 42  HCPCS_CD_4                      0 non-null      object
 43  HCPCS_CD_5                      0 non-null      object
 44  HCPCS_CD_6                      0 non-null      object
 45  HCPCS_CD_7                      0 non-null      object
 46  HCPCS_CD_8                      0 non-null      object
 47  HCPCS_CD_9                      0 non-null      object
 48  HCPCS_CD_10                     0 non-null      object
 49  HCPCS_CD_11                     0 non-null      object
 50  HCPCS_CD_12                     0 non-null      object
 51  HCPCS_CD_13                     0 non-null      object
 52  HCPCS_CD_14                     0 non-null      object
 53  HCPCS_CD_15                     0 non-null      object
 54  HCPCS_CD_16                     0 non-null      object
 55  HCPCS_CD_17                     0 non-null      object
 56  HCPCS_CD_18                     0 non-null      object
 57  HCPCS_CD_19                     0 non-null      object
 58  HCPCS_CD_20                     0 non-null      object
 59  HCPCS_CD_21                     0 non-null      object
 60  HCPCS_CD_22                     0 non-null      object
 61  HCPCS_CD_23                     0 non-null      object
 62  HCPCS_CD_24                     0 non-null      object
 63  HCPCS_CD_25                     0 non-null      object
 64  HCPCS_CD_26                     0 non-null      object
 65  HCPCS_CD_27                     0 non-null      object
 66  HCPCS_CD_28                     0 non-null      object
 67  HCPCS_CD_29                     0 non-null      object
 68  HCPCS_CD_30                     0 non-null      object
 69  HCPCS_CD_31                     0 non-null      object
 70  HCPCS_CD_32                     0 non-null      object
 71  HCPCS_CD_33                     0 non-null      object
 72  HCPCS_CD_34                     0 non-null      object
 73  HCPCS_CD_35                     0 non-null      object
 74  HCPCS_CD_36                     0 non-null      object
 75  HCPCS_CD_37                     0 non-null      object
 76  HCPCS_CD_38                     0 non-null      object
 77  HCPCS_CD_39                     0 non-null      object
 78  HCPCS_CD_40                     0 non-null      object
 79  HCPCS_CD_41                     0 non-null      object
 80  HCPCS_CD_42                     0 non-null      object
 81  HCPCS_CD_43                     0 non-null      object
 82  HCPCS_CD_44                     0 non-null      object
 83  HCPCS_CD_45                     0 non-null      object
dtypes: Int64(1), bool(1), datetime64[ns](4), float64(11), int64(1), object(66)
memory usage: 42.9+ MB

In [8]:
inpatient_clean = inpatient_clean.reset_index(drop=True)

In [9]:
inpatient_clean.loc[
    inpatient_clean["claim_start_date"].isna(),
    ["claim_id", "admission_date", "discharge_date"]
].head()

             claim_id admission_date discharge_date
1775  196901176966106     2008-06-10     2008-07-15
2578  196531176970382     2009-01-24     2009-02-28
4066  196821176998887     2009-08-12     2009-09-16
5700  196101177023665     2008-11-18     2008-12-23
6064  196231176993156     2008-05-28     2008-07-02

In [10]:
len(inpatient_clean), inpatient_clean["claim_id"].nunique()

(66705, 66705)

In [12]:
hcpcs_cols = [c for c in inpatient_clean.columns if c.startswith("HCPCS_CD_")]
inpatient_clean = inpatient_clean.drop(columns=hcpcs_cols)
inpatient_clean = inpatient_clean.reset_index(drop=True)
inpatient_clean.to_csv(
    "stg_inpatient_claims_clean.csv",
    index=False
)

In [10]:
import pandas as pd
from typing import Optional

OUTPATIENT_RENAME_MAP = {
    "DESYNPUF_ID": "beneficiary_id",
    "CLM_ID": "claim_id",
    "PRVDR_NUM": "provider_id",

    "CLM_FROM_DT": "claim_start_date",
    "CLM_THRU_DT": "claim_end_date",

    "CLM_PMT_AMT": "medicare_payment_amount",
    "NCH_PRMRY_PYR_CLM_PD_AMT": "primary_payer_paid_amount",

    "NCH_BENE_BLOOD_DDCTBL_LBLTY_AM": "blood_deductible_liability_amount",
    "NCH_BENE_PTB_DDCTBL_AMT": "part_b_deductible_amount",
    "NCH_BENE_PTB_COINSRNC_AMT": "part_b_coinsurance_amount",

    "ADMTNG_ICD9_DGNS_CD": "primary_diagnosis",
}

OUTPATIENT_DATE_COLS = ["claim_start_date", "claim_end_date"]

OUTPATIENT_NUMERIC_COLS = [
    "medicare_payment_amount",
    "primary_payer_paid_amount",
    "blood_deductible_liability_amount",
    "part_b_deductible_amount",
    "part_b_coinsurance_amount",
]

OUTPATIENT_REQUIRED_COLS = ["beneficiary_id", "claim_id", "claim_start_date"]


def _parse_yyyymmdd(series: pd.Series, fmt: str = "%Y%m%d") -> pd.Series:
    s = series.copy()
    if pd.api.types.is_numeric_dtype(s):
        s = s.astype("Int64").astype(str)
    else:
        s = s.astype(str).str.strip()
    return pd.to_datetime(s, format=fmt, errors="coerce")


def clean_outpatient_claims(
    df: pd.DataFrame,
    year_hint: Optional[int] = None,
    date_format: str = "%Y%m%d",
    drop_all_null_hcpcs: bool = False,
) -> pd.DataFrame:
    """
    Clean + standardise DE-SynPUF outpatient claims at claim-grain (1 row = 1 claim).
    Produces stg_outpatient_claims_clean.
    """
    df = df.copy()

    # 0) Normalize headers
    df.columns = df.columns.astype(str).str.strip()

    # 1) Rename (present only)
    rename_present = {k: v for k, v in OUTPATIENT_RENAME_MAP.items() if k in df.columns}
    df = df.rename(columns=rename_present)

    # 2) Parse dates
    for c in OUTPATIENT_DATE_COLS:
        if c in df.columns:
            df[c] = _parse_yyyymmdd(df[c], fmt=date_format)

    # 3) Clean numerics
    for c in OUTPATIENT_NUMERIC_COLS:
        if c in df.columns:
            df[c] = pd.to_numeric(df[c], errors="coerce")

    # 4) Strip IDs/codes
    for c in ["beneficiary_id", "claim_id", "provider_id", "primary_diagnosis"]:
        if c in df.columns:
            df[c] = df[c].astype(str).str.strip().replace({"": pd.NA})

    # 5) Drop bad rows missing required fields
    present_required = [c for c in OUTPATIENT_REQUIRED_COLS if c in df.columns]
    if present_required:
        df = df.dropna(subset=present_required).copy()

    # 6) Year (use claim_start_date year)
    if "claim_start_date" in df.columns:
        df["year"] = df["claim_start_date"].dt.year.astype("Int64")
    elif year_hint is not None:
        df["year"] = pd.Series([year_hint] * len(df), dtype="Int64")

    # 7) Claim grain check: remove duplicates by claim_id
    if "claim_id" in df.columns:
        dup_mask = df["claim_id"].duplicated(keep="first")
        df["claim_id_duplicated_flag"] = dup_mask
        df = df[~dup_mask].copy()
    else:
        df["claim_id_duplicated_flag"] = False

    # 8) Optional: clean code columns (ICD/HCPCS) whitespace
    code_prefixes = ("ICD9_DGNS_CD_", "ICD9_PRCDR_CD_", "HCPCS_CD_")
    for c in df.columns:
        if c.startswith(code_prefixes):
            df[c] = df[c].astype(str).str.strip().replace({"": pd.NA, "nan": pd.NA, "None": pd.NA})

    # 9) Optional: drop HCPCS columns that are ALL null (only do this after checking!)
    if drop_all_null_hcpcs:
        hcpcs_cols = [c for c in df.columns if c.startswith("HCPCS_CD_")]
        all_null = [c for c in hcpcs_cols if df[c].notna().sum() == 0]
        if all_null:
            df = df.drop(columns=all_null)

    # 10) Order core columns first
    core_order = [
        "claim_id",
        "beneficiary_id",
        "provider_id",
        "claim_start_date",
        "claim_end_date",
        "year",
        "primary_diagnosis",
        "medicare_payment_amount",
        "primary_payer_paid_amount",
        "part_b_deductible_amount",
        "part_b_coinsurance_amount",
        "blood_deductible_liability_amount",
        "claim_id_duplicated_flag",
        "SEGMENT",  # keep if present, optional
        "AT_PHYSN_NPI",
        "OP_PHYSN_NPI",
        "OT_PHYSN_NPI",
    ]
    existing_core = [c for c in core_order if c in df.columns]
    remaining = [c for c in df.columns if c not in existing_core]
    return df[existing_core + remaining]

In [11]:
outpatient_clean = clean_outpatient_claims(outpatient)

outpatient_clean.info()
len(outpatient_clean), outpatient_clean["claim_id"].nunique()

<class 'pandas.core.frame.DataFrame'>
Index: 779537 entries, 0 to 790789
Data columns (total 78 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   claim_id                           779537 non-null  object
 1   beneficiary_id                     779537 non-null  object
 2   provider_id                        779537 non-null  object
 3   claim_start_date                   779537 non-null  datetime64[ns]
 4   claim_end_date                     779537 non-null  datetime64[ns]
 5   year                               779537 non-null  Int64
 6   primary_diagnosis                  779537 non-null  object
 7   medicare_payment_amount            779537 non-null  Float64
 8   primary_payer_paid_amount          779537 non-null  Float64
 9   part_b_deductible_amount           779537 non-null  Float64
 10  part_b_coinsurance_amount          779537 non-null  Float64
 11  blood_deductible_liability_amount  779537 non-null  Float64
 12  claim_id_duplicated_flag           779537 non-null  bool
 13  SEGMENT                            779537 non-null  string
 14  AT_PHYSN_NPI                       773000 non-null  string
 15  OP_PHYSN_NPI                       134433 non-null  string
 16  OT_PHYSN_NPI                       257666 non-null  string
 17  ICD9_DGNS_CD_1                     779537 non-null  object
 18  ICD9_DGNS_CD_2                     779537 non-null  object
 19  ICD9_DGNS_CD_3                     779537 non-null  object
 20  ICD9_DGNS_CD_4                     779537 non-null  object
 21  ICD9_DGNS_CD_5                     779537 non-null  object
 22  ICD9_DGNS_CD_6                     779537 non-null  object
 23  ICD9_DGNS_CD_7                     779537 non-null  object
 24  ICD9_DGNS_CD_8                     779537 non-null  object
 25  ICD9_DGNS_CD_9                     779537 non-null  object
 26  ICD9_DGNS_CD_10                    779537 non-null  object
 27  ICD9_PRCDR_CD_1                    779537 non-null  object
 28  ICD9_PRCDR_CD_2                    779537 non-null  object
 29  ICD9_PRCDR_CD_3                    779537 non-null  object
 30  ICD9_PRCDR_CD_4                    779537 non-null  object
 31  ICD9_PRCDR_CD_5                    779537 non-null  object
 32  ICD9_PRCDR_CD_6                    779537 non-null  object
 33  HCPCS_CD_1                         779537 non-null  object
 34  HCPCS_CD_2                         779537 non-null  object
 35  HCPCS_CD_3                         779537 non-null  object
 36  HCPCS_CD_4                         779537 non-null  object
 37  HCPCS_CD_5                         779537 non-null  object
 38  HCPCS_CD_6                         779537 non-null  object
 39  HCPCS_CD_7                         779537 non-null  object
 40  HCPCS_CD_8                         779537 non-null  object
 41  HCPCS_CD_9                         779537 non-null  object
 42  HCPCS_CD_10                        779537 non-null  object
 43  HCPCS_CD_11                        779537 non-null  object
 44  HCPCS_CD_12                        779537 non-null  object
 45  HCPCS_CD_13                        779537 non-null  object
 46  HCPCS_CD_14                        779537 non-null  object
 47  HCPCS_CD_15                        779537 non-null  object
 48  HCPCS_CD_16                        779537 non-null  object
 49  HCPCS_CD_17                        779537 non-null  object
 50  HCPCS_CD_18                        779537 non-null  object
 51  HCPCS_CD_19                        779537 non-null  object
 52  HCPCS_CD_20                        779537 non-null  object
 53  HCPCS_CD_21                        779537 non-null  object
 54  HCPCS_CD_22                        779537 non-null  object
 55  HCPCS_CD_23                        779537 non-null  object
 56  HCPCS_CD_24                        779537 non-null  object
 57  HCPCS_CD_25                        779537 non-null  object
 58  HCPCS_CD_26                        779537 non-null  object
 59  HCPCS_CD_27                        779537 non-null  object
 60  HCPCS_CD_28                        779537 non-null  object
 61  HCPCS_CD_29                        779537 non-null  object
 62  HCPCS_CD_30                        779537 non-null  object
 63  HCPCS_CD_31                        779537 non-null  object
 64  HCPCS_CD_32                        779537 non-null  object
 65  HCPCS_CD_33                        779537 non-null  object
 66  HCPCS_CD_34                        779537 non-null  object
 67  HCPCS_CD_35                        779537 non-null  object
 68  HCPCS_CD_36                        779537 non-null  object
 69  HCPCS_CD_37                        779537 non-null  object
 70  HCPCS_CD_38                        779537 non-null  object
 71  HCPCS_CD_39                        779537 non-null  object
 72  HCPCS_CD_40                        779537 non-null  object
 73  HCPCS_CD_41                        779537 non-null  object
 74  HCPCS_CD_42                        779537 non-null  object
 75  HCPCS_CD_43                        779537 non-null  object
 76  HCPCS_CD_44                        779537 non-null  object
 77  HCPCS_CD_45                        779537 non-null  object
dtypes: Float64(5), Int64(1), bool(1), datetime64[ns](2), object(65), string(4)
memory usage: 469.1+ MB

(779537, 779537)

In [12]:
outpatient_clean.to_csv(
    "stg_outpatient_claims_clean.csv",
    index=False
)

In [13]:
len(outpatient), len(outpatient_clean), len(outpatient) - len(outpatient_clean)

(790790, 779537, 11253)

In [15]:
len(outpatient), outpatient["CLM_ID"].nunique()

(790790, 779815)

In [18]:
# Rows dropped that were NOT duplicates
dropped_non_dup = outpatient.loc[
    ~outpatient["CLM_ID"].isin(outpatient_clean["claim_id"])
].copy()

# Remove the known duplicate-claim-id rows
dropped_non_dup = dropped_non_dup.loc[
    ~dropped_non_dup.duplicated(subset=["CLM_ID"], keep=False)
]

len(dropped_non_dup)  # should be 278

278

In [21]:
summary = {
    "missing_beneficiary_id": dropped_non_dup["DESYNPUF_ID"].isna().sum(),
    "missing_provider_id": dropped_non_dup["PRVDR_NUM"].isna().sum(),
    "missing_start_date": dropped_non_dup["CLM_FROM_DT"].isna().sum(),
    "missing_end_date": dropped_non_dup["CLM_THRU_DT"].isna().sum(),
    "end_before_start": (dropped_non_dup["CLM_THRU_DT"] < dropped_non_dup["CLM_FROM_DT"]).sum(),
}

summary

{'missing_beneficiary_id': 0,
 'missing_provider_id': 0,
 'missing_start_date': 278,
 'missing_end_date': 278,
 'end_before_start': 0}

In [1]:
import pandas as pd

path = r"C:\Users\Dell\Portfolio\insurance-claims-analytics\Notebooks\stg_beneficiary_all_clean.csv"

df = pd.read_csv(path, nrows=0)   # read header only

cols = df.columns.tolist()

def q(s):
    return '"' + s.replace('"','""') + '"'

sql = "DROP TABLE IF EXISTS public.stg_beneficiary_all_clean;\n"
sql += "CREATE TABLE public.stg_beneficiary_all_clean (\n"
sql += ",\n".join([f"    {q(c)} text" for c in cols])
sql += "\n);\n"

print(sql)

DROP TABLE IF EXISTS public.stg_beneficiary_all_clean;
CREATE TABLE public.stg_beneficiary_all_clean (
    "beneficiary_id" text,
    "birth_date" text,
    "death_date" text,
    "sex_code" text,
    "race_code" text,
    "esrd_indicator" text,
    "state_code" text,
    "county_code" text,
    "part_a_coverage_months" text,
    "part_b_coverage_months" text,
    "hmo_coverage_months" text,
    "total_coverage_months" text,
    "chronic_alzheimer" text,
    "chronic_heart_failure" text,
    "chronic_kidney_disease" text,
    "chronic_cancer" text,
    "chronic_copd" text,
    "chronic_depression" text,
    "chronic_diabetes" text,
    "chronic_ischemic_heart_disease" text,
    "chronic_osteoporosis" text,
    "chronic_rheumatoid_arthritis_osteoarthritis" text,
    "chronic_stroke_tia" text,
    "medicare_payment_inpatient" text,
    "beneficiary_payment_inpatient" text,
    "third_party_payment_inpatient" text,
    "medicare_payment_outpatient" text,
    "beneficiary_payment_outpatient" text,
    "third_party_payment_outpatient" text,
    "medicare_payment_carrier" text,
    "beneficiary_payment_carrier" text,
    "third_party_payment_carrier" text,
    "year" text,
    "age_at_year" text,
    "is_alive_flag" text,
    "chronic_condition_count" text,
    "total_medicare_payment" text,
    "total_beneficiary_payment" text,
    "total_third_party_payment" text,
    "total_payment" text
);

“continue

In [4]:
import pandas as pd

path = r"C:\Users\Dell\Portfolio\insurance-claims-analytics\Notebooks\stg_inpatient_claims_clean.csv"

df = pd.read_csv(path, nrows=0)
cols = df.columns.tolist()

def q(s):
    return '"' + s.replace('"','""') + '"'

sql = "DROP TABLE IF EXISTS public.stg_inpatient_claims_clean;\n"
sql += "CREATE TABLE public.stg_inpatient_claims_clean (\n"
sql += ",\n".join([f"    {q(c)} text" for c in cols])
sql += "\n);\n"

print(sql)

DROP TABLE IF EXISTS public.stg_inpatient_claims_clean;
CREATE TABLE public.stg_inpatient_claims_clean (
    "claim_id" text,
    "beneficiary_id" text,
    "provider_id" text,
    "admission_date" text,
    "discharge_date" text,
    "claim_start_date" text,
    "claim_end_date" text,
    "year" text,
    "length_of_stay" text,
    "utilization_days" text,
    "drg_code" text,
    "primary_diagnosis" text,
    "medicare_payment_amount" text,
    "primary_payer_paid_amount" text,
    "claim_id_duplicated_flag" text,
    "SEGMENT" text,
    "AT_PHYSN_NPI" text,
    "OP_PHYSN_NPI" text,
    "OT_PHYSN_NPI" text,
    "CLM_PASS_THRU_PER_DIEM_AMT" text,
    "NCH_BENE_IP_DDCTBL_AMT" text,
    "NCH_BENE_PTA_COINSRNC_LBLTY_AM" text,
    "NCH_BENE_BLOOD_DDCTBL_LBLTY_AM" text,
    "ICD9_DGNS_CD_1" text,
    "ICD9_DGNS_CD_2" text,
    "ICD9_DGNS_CD_3" text,
    "ICD9_DGNS_CD_4" text,
    "ICD9_DGNS_CD_5" text,
    "ICD9_DGNS_CD_6" text,
    "ICD9_DGNS_CD_7" text,
    "ICD9_DGNS_CD_8" text,
    "ICD9_DGNS_CD_9" text,
    "ICD9_DGNS_CD_10" text,
    "ICD9_PRCDR_CD_1" text,
    "ICD9_PRCDR_CD_2" text,
    "ICD9_PRCDR_CD_3" text,
    "ICD9_PRCDR_CD_4" text,
    "ICD9_PRCDR_CD_5" text,
    "ICD9_PRCDR_CD_6" text
);

In [5]:
import pandas as pd

path = r"C:\Users\Dell\Portfolio\insurance-claims-analytics\Notebooks\stg_outpatient_claims_clean.csv"

df = pd.read_csv(path, nrows=0)
cols = df.columns.tolist()

def q(s):
    return '"' + s.replace('"','""') + '"'

sql = "DROP TABLE IF EXISTS public.stg_outpatient_claims_clean;\n"
sql += "CREATE TABLE public.stg_outpatient_claims_clean (\n"
sql += ",\n".join([f"    {q(c)} text" for c in cols])
sql += "\n);\n"

print(sql)

DROP TABLE IF EXISTS public.stg_outpatient_claims_clean;
CREATE TABLE public.stg_outpatient_claims_clean (
    "claim_id" text,
    "beneficiary_id" text,
    "provider_id" text,
    "claim_start_date" text,
    "claim_end_date" text,
    "year" text,
    "primary_diagnosis" text,
    "medicare_payment_amount" text,
    "primary_payer_paid_amount" text,
    "part_b_deductible_amount" text,
    "part_b_coinsurance_amount" text,
    "blood_deductible_liability_amount" text,
    "claim_id_duplicated_flag" text,
    "SEGMENT" text,
    "AT_PHYSN_NPI" text,
    "OP_PHYSN_NPI" text,
    "OT_PHYSN_NPI" text,
    "ICD9_DGNS_CD_1" text,
    "ICD9_DGNS_CD_2" text,
    "ICD9_DGNS_CD_3" text,
    "ICD9_DGNS_CD_4" text,
    "ICD9_DGNS_CD_5" text,
    "ICD9_DGNS_CD_6" text,
    "ICD9_DGNS_CD_7" text,
    "ICD9_DGNS_CD_8" text,
    "ICD9_DGNS_CD_9" text,
    "ICD9_DGNS_CD_10" text,
    "ICD9_PRCDR_CD_1" text,
    "ICD9_PRCDR_CD_2" text,
    "ICD9_PRCDR_CD_3" text,
    "ICD9_PRCDR_CD_4" text,
    "ICD9_PRCDR_CD_5" text,
    "ICD9_PRCDR_CD_6" text,
    "HCPCS_CD_1" text,
    "HCPCS_CD_2" text,
    "HCPCS_CD_3" text,
    "HCPCS_CD_4" text,
    "HCPCS_CD_5" text,
    "HCPCS_CD_6" text,
    "HCPCS_CD_7" text,
    "HCPCS_CD_8" text,
    "HCPCS_CD_9" text,
    "HCPCS_CD_10" text,
    "HCPCS_CD_11" text,
    "HCPCS_CD_12" text,
    "HCPCS_CD_13" text,
    "HCPCS_CD_14" text,
    "HCPCS_CD_15" text,
    "HCPCS_CD_16" text,
    "HCPCS_CD_17" text,
    "HCPCS_CD_18" text,
    "HCPCS_CD_19" text,
    "HCPCS_CD_20" text,
    "HCPCS_CD_21" text,
    "HCPCS_CD_22" text,
    "HCPCS_CD_23" text,
    "HCPCS_CD_24" text,
    "HCPCS_CD_25" text,
    "HCPCS_CD_26" text,
    "HCPCS_CD_27" text,
    "HCPCS_CD_28" text,
    "HCPCS_CD_29" text,
    "HCPCS_CD_30" text,
    "HCPCS_CD_31" text,
    "HCPCS_CD_32" text,
    "HCPCS_CD_33" text,
    "HCPCS_CD_34" text,
    "HCPCS_CD_35" text,
    "HCPCS_CD_36" text,
    "HCPCS_CD_37" text,
    "HCPCS_CD_38" text,
    "HCPCS_CD_39" text,
    "HCPCS_CD_40" text,
    "HCPCS_CD_41" text,
    "HCPCS_CD_42" text,
    "HCPCS_CD_43" text,
    "HCPCS_CD_44" text,
    "HCPCS_CD_45" text
);

“continue warehouse project”